// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: burro/v1/burro.proto

package burrov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_burro_v1_burro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burro_v1_burro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_burro_v1_burro_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_burro_v1_burro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burro_v1_burro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_burro_v1_burro_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType []TransportType        `protobuf:"varint,1,rep,packed,name=transport_type,json=transportType,proto3,enum=burro.v1.TransportType" json:"transport_type,omitempty"`
	EventTypes    []EventType            `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=burro.v1.EventType" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_burro_v1_burro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burro_v1_burro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_burro_v1_burro_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTransportType() []TransportType {
	if x != nil {
		return x.TransportType
	}
	return nil
}

func (x *SubscribeRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_burro_v1_burro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burro_v1_burro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_burro_v1_burro_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_burro_v1_burro_proto protoreflect.FileDescriptor

const file_burro_v1_burro_proto_rawDesc = "" +
	"\n" +
	"\x14burro/v1/burro.proto\x12\bburro.v1\x1a\x14burro/v1/types.proto\x1a\x14burro/v1/event.proto\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x88\x01\n" +
	"\x10SubscribeRequest\x12>\n" +
	"\x0etransport_type\x18\x01 \x03(\x0e2\x17.burro.v1.TransportTypeR\rtransportType\x124\n" +
	"\vevent_types\x18\x02 \x03(\x0e2\x13.burro.v1.EventTypeR\n" +
	"eventTypes\":\n" +
	"\x11SubscribeResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.burro.v1.EventR\x05event2\x8d\x01\n" +
	"\fBurroService\x125\n" +
	"\x04Ping\x12\x15.burro.v1.PingRequest\x1a\x16.burro.v1.PingResponse\x12F\n" +
	"\tSubscribe\x12\x1a.burro.v1.SubscribeRequest\x1a\x1b.burro.v1.SubscribeResponse0\x01B9Z7gitlab.com/marsskom/burro-proto/gen/go/burro/v1;burrov1b\x06proto3"

var (
	file_burro_v1_burro_proto_rawDescOnce sync.Once
	file_burro_v1_burro_proto_rawDescData []byte
)

func file_burro_v1_burro_proto_rawDescGZIP() []byte {
	file_burro_v1_burro_proto_rawDescOnce.Do(func() {
		file_burro_v1_burro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_burro_v1_burro_proto_rawDesc), len(file_burro_v1_burro_proto_rawDesc)))
	})
	return file_burro_v1_burro_proto_rawDescData
}

var file_burro_v1_burro_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_burro_v1_burro_proto_goTypes = []any{
	(*PingRequest)(nil),       // 0: burro.v1.PingRequest
	(*PingResponse)(nil),      // 1: burro.v1.PingResponse
	(*SubscribeRequest)(nil),  // 2: burro.v1.SubscribeRequest
	(*SubscribeResponse)(nil), // 3: burro.v1.SubscribeResponse
	(TransportType)(0),        // 4: burro.v1.TransportType
	(EventType)(0),            // 5: burro.v1.EventType
	(*Event)(nil),             // 6: burro.v1.Event
}
var file_burro_v1_burro_proto_depIdxs = []int32{
	4, // 0: burro.v1.SubscribeRequest.transport_type:type_name -> burro.v1.TransportType
	5, // 1: burro.v1.SubscribeRequest.event_types:type_name -> burro.v1.EventType
	6, // 2: burro.v1.SubscribeResponse.event:type_name -> burro.v1.Event
	0, // 3: burro.v1.BurroService.Ping:input_type -> burro.v1.PingRequest
	2, // 4: burro.v1.BurroService.Subscribe:input_type -> burro.v1.SubscribeRequest
	1, // 5: burro.v1.BurroService.Ping:output_type -> burro.v1.PingResponse
	3, // 6: burro.v1.BurroService.Subscribe:output_type -> burro.v1.SubscribeResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_burro_v1_burro_proto_init() }
func file_burro_v1_burro_proto_init() {
	if File_burro_v1_burro_proto != nil {
		return
	}
	file_burro_v1_types_proto_init()
	file_burro_v1_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_burro_v1_burro_proto_rawDesc), len(file_burro_v1_burro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_burro_v1_burro_proto_goTypes,
		DependencyIndexes: file_burro_v1_burro_proto_depIdxs,
		MessageInfos:      file_burro_v1_burro_proto_msgTypes,
	}.Build()
	File_burro_v1_burro_proto = out.File
	file_burro_v1_burro_proto_goTypes = nil
	file_burro_v1_burro_proto_depIdxs = nil
}
