// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: burro/v1/event.proto

package burrov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType TransportType          `protobuf:"varint,1,opt,name=transport_type,json=transportType,proto3,enum=burro.v1.TransportType" json:"transport_type,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=burro.v1.EventType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Http          *HTTPEvent             `protobuf:"bytes,6,opt,name=http,proto3" json:"http,omitempty"`
	Ws            *WSEvent               `protobuf:"bytes,7,opt,name=ws,proto3" json:"ws,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_burro_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_burro_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_burro_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTransportType() TransportType {
	if x != nil {
		return x.TransportType
	}
	return TransportType_TRANSPORT_TYPE_UNSPECIFIED
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetHttp() *HTTPEvent {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Event) GetWs() *WSEvent {
	if x != nil {
		return x.Ws
	}
	return nil
}

var File_burro_v1_event_proto protoreflect.FileDescriptor

const file_burro_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14burro/v1/event.proto\x12\bburro.v1\x1a\x14burro/v1/types.proto\x1a\x13burro/v1/http.proto\x1a\x11burro/v1/ws.proto\"\x89\x02\n" +
	"\x05Event\x12>\n" +
	"\x0etransport_type\x18\x01 \x01(\x0e2\x17.burro.v1.TransportTypeR\rtransportType\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.burro.v1.EventTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12'\n" +
	"\x04http\x18\x06 \x01(\v2\x13.burro.v1.HTTPEventR\x04http\x12!\n" +
	"\x02ws\x18\a \x01(\v2\x11.burro.v1.WSEventR\x02wsB9Z7gitlab.com/marsskom/burro-proto/gen/go/burro/v1;burrov1b\x06proto3"

var (
	file_burro_v1_event_proto_rawDescOnce sync.Once
	file_burro_v1_event_proto_rawDescData []byte
)

func file_burro_v1_event_proto_rawDescGZIP() []byte {
	file_burro_v1_event_proto_rawDescOnce.Do(func() {
		file_burro_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_burro_v1_event_proto_rawDesc), len(file_burro_v1_event_proto_rawDesc)))
	})
	return file_burro_v1_event_proto_rawDescData
}

var file_burro_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_burro_v1_event_proto_goTypes = []any{
	(*Event)(nil),      // 0: burro.v1.Event
	(TransportType)(0), // 1: burro.v1.TransportType
	(EventType)(0),     // 2: burro.v1.EventType
	(*HTTPEvent)(nil),  // 3: burro.v1.HTTPEvent
	(*WSEvent)(nil),    // 4: burro.v1.WSEvent
}
var file_burro_v1_event_proto_depIdxs = []int32{
	1, // 0: burro.v1.Event.transport_type:type_name -> burro.v1.TransportType
	2, // 1: burro.v1.Event.type:type_name -> burro.v1.EventType
	3, // 2: burro.v1.Event.http:type_name -> burro.v1.HTTPEvent
	4, // 3: burro.v1.Event.ws:type_name -> burro.v1.WSEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_burro_v1_event_proto_init() }
func file_burro_v1_event_proto_init() {
	if File_burro_v1_event_proto != nil {
		return
	}
	file_burro_v1_types_proto_init()
	file_burro_v1_http_proto_init()
	file_burro_v1_ws_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_burro_v1_event_proto_rawDesc), len(file_burro_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_burro_v1_event_proto_goTypes,
		DependencyIndexes: file_burro_v1_event_proto_depIdxs,
		MessageInfos:      file_burro_v1_event_proto_msgTypes,
	}.Build()
	File_burro_v1_event_proto = out.File
	file_burro_v1_event_proto_goTypes = nil
	file_burro_v1_event_proto_depIdxs = nil
}
