// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: burro/v1/types.proto

package burrov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportType int32

const (
	TransportType_TRANSPORT_TYPE_UNSPECIFIED TransportType = 0
	TransportType_TRANSPORT_TYPE_HTTP        TransportType = 1
	TransportType_TRANSPORT_TYPE_WS          TransportType = 2
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_TYPE_UNSPECIFIED",
		1: "TRANSPORT_TYPE_HTTP",
		2: "TRANSPORT_TYPE_WS",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_TYPE_UNSPECIFIED": 0,
		"TRANSPORT_TYPE_HTTP":        1,
		"TRANSPORT_TYPE_WS":          2,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_burro_v1_types_proto_enumTypes[0].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_burro_v1_types_proto_enumTypes[0]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_burro_v1_types_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CONNECT     EventType = 1
	EventType_EVENT_TYPE_REQUEST     EventType = 2
	EventType_EVENT_TYPE_RESPONSE    EventType = 3
	EventType_EVENT_TYPE_ERROR       EventType = 4
	EventType_EVENT_TYPE_CLOSE       EventType = 5
	EventType_EVENT_TYPE_WS_CONNECT  EventType = 10
	EventType_EVENT_TYPE_WS_MESSAGE  EventType = 11
	EventType_EVENT_TYPE_WS_CLOSE    EventType = 12
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_CONNECT",
		2:  "EVENT_TYPE_REQUEST",
		3:  "EVENT_TYPE_RESPONSE",
		4:  "EVENT_TYPE_ERROR",
		5:  "EVENT_TYPE_CLOSE",
		10: "EVENT_TYPE_WS_CONNECT",
		11: "EVENT_TYPE_WS_MESSAGE",
		12: "EVENT_TYPE_WS_CLOSE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CONNECT":     1,
		"EVENT_TYPE_REQUEST":     2,
		"EVENT_TYPE_RESPONSE":    3,
		"EVENT_TYPE_ERROR":       4,
		"EVENT_TYPE_CLOSE":       5,
		"EVENT_TYPE_WS_CONNECT":  10,
		"EVENT_TYPE_WS_MESSAGE":  11,
		"EVENT_TYPE_WS_CLOSE":    12,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_burro_v1_types_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_burro_v1_types_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_burro_v1_types_proto_rawDescGZIP(), []int{1}
}

var File_burro_v1_types_proto protoreflect.FileDescriptor

const file_burro_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14burro/v1/types.proto\x12\bburro.v1*_\n" +
	"\rTransportType\x12\x1e\n" +
	"\x1aTRANSPORT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRANSPORT_TYPE_HTTP\x10\x01\x12\x15\n" +
	"\x11TRANSPORT_TYPE_WS\x10\x02*\xeb\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CONNECT\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_REQUEST\x10\x02\x12\x17\n" +
	"\x13EVENT_TYPE_RESPONSE\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x04\x12\x14\n" +
	"\x10EVENT_TYPE_CLOSE\x10\x05\x12\x19\n" +
	"\x15EVENT_TYPE_WS_CONNECT\x10\n" +
	"\x12\x19\n" +
	"\x15EVENT_TYPE_WS_MESSAGE\x10\v\x12\x17\n" +
	"\x13EVENT_TYPE_WS_CLOSE\x10\fB9Z7gitlab.com/marsskom/burro-proto/gen/go/burro/v1;burrov1b\x06proto3"

var (
	file_burro_v1_types_proto_rawDescOnce sync.Once
	file_burro_v1_types_proto_rawDescData []byte
)

func file_burro_v1_types_proto_rawDescGZIP() []byte {
	file_burro_v1_types_proto_rawDescOnce.Do(func() {
		file_burro_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_burro_v1_types_proto_rawDesc), len(file_burro_v1_types_proto_rawDesc)))
	})
	return file_burro_v1_types_proto_rawDescData
}

var file_burro_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_burro_v1_types_proto_goTypes = []any{
	(TransportType)(0), // 0: burro.v1.TransportType
	(EventType)(0),     // 1: burro.v1.EventType
}
var file_burro_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_burro_v1_types_proto_init() }
func file_burro_v1_types_proto_init() {
	if File_burro_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_burro_v1_types_proto_rawDesc), len(file_burro_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_burro_v1_types_proto_goTypes,
		DependencyIndexes: file_burro_v1_types_proto_depIdxs,
		EnumInfos:         file_burro_v1_types_proto_enumTypes,
	}.Build()
	File_burro_v1_types_proto = out.File
	file_burro_v1_types_proto_goTypes = nil
	file_burro_v1_types_proto_depIdxs = nil
}
