// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: burro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_burro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_burro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_burro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Type                  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SessionId             string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Proto                 string                 `protobuf:"bytes,4,opt,name=proto,proto3" json:"proto,omitempty"`
	Scheme                string                 `protobuf:"bytes,5,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host                  string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	Method                string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	Url                   string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Path                  string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	ContentLength         int64                  `protobuf:"varint,10,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	RemoteAddr            string                 `protobuf:"bytes,11,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	StartTime             int64                  `protobuf:"varint,12,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	State                 int32                  `protobuf:"varint,13,opt,name=state,proto3" json:"state,omitempty"`
	IsFinished            bool                   `protobuf:"varint,14,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	QueryParams           string                 `protobuf:"bytes,15,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"` // JSON
	Headers               string                 `protobuf:"bytes,16,opt,name=headers,proto3" json:"headers,omitempty"`                            // JSON
	Cookies               string                 `protobuf:"bytes,17,opt,name=cookies,proto3" json:"cookies,omitempty"`                            // JSON
	RequestBody           []byte                 `protobuf:"bytes,18,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseStatus        string                 `protobuf:"bytes,19,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseStatusCode    int32                  `protobuf:"varint,20,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	ResponseProto         string                 `protobuf:"bytes,21,opt,name=response_proto,json=responseProto,proto3" json:"response_proto,omitempty"`
	ResponseHeaders       string                 `protobuf:"bytes,22,opt,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty"` // JSON
	ResponseContentLength int64                  `protobuf:"varint,23,opt,name=response_content_length,json=responseContentLength,proto3" json:"response_content_length,omitempty"`
	ResponseBody          []byte                 `protobuf:"bytes,24,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             int64                  `protobuf:"varint,26,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata              string                 `protobuf:"bytes,27,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_burro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Event) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Event) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Event) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Event) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Event) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Event) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Event) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Event) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Event) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Event) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *Event) GetQueryParams() string {
	if x != nil {
		return x.QueryParams
	}
	return ""
}

func (x *Event) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *Event) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *Event) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *Event) GetResponseStatus() string {
	if x != nil {
		return x.ResponseStatus
	}
	return ""
}

func (x *Event) GetResponseStatusCode() int32 {
	if x != nil {
		return x.ResponseStatusCode
	}
	return 0
}

func (x *Event) GetResponseProto() string {
	if x != nil {
		return x.ResponseProto
	}
	return ""
}

func (x *Event) GetResponseHeaders() string {
	if x != nil {
		return x.ResponseHeaders
	}
	return ""
}

func (x *Event) GetResponseContentLength() int64 {
	if x != nil {
		return x.ResponseContentLength
	}
	return 0
}

func (x *Event) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Event) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_burro_proto protoreflect.FileDescriptor

const file_burro_proto_rawDesc = "" +
	"\n" +
	"\vburro.proto\x12\x05burro\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xc6\x06\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05proto\x18\x04 \x01(\tR\x05proto\x12\x16\n" +
	"\x06scheme\x18\x05 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12%\n" +
	"\x0econtent_length\x18\n" +
	" \x01(\x03R\rcontentLength\x12\x1f\n" +
	"\vremote_addr\x18\v \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"start_time\x18\f \x01(\x03R\tstartTime\x12\x14\n" +
	"\x05state\x18\r \x01(\x05R\x05state\x12\x1f\n" +
	"\vis_finished\x18\x0e \x01(\bR\n" +
	"isFinished\x12!\n" +
	"\fquery_params\x18\x0f \x01(\tR\vqueryParams\x12\x18\n" +
	"\aheaders\x18\x10 \x01(\tR\aheaders\x12\x18\n" +
	"\acookies\x18\x11 \x01(\tR\acookies\x12!\n" +
	"\frequest_body\x18\x12 \x01(\fR\vrequestBody\x12'\n" +
	"\x0fresponse_status\x18\x13 \x01(\tR\x0eresponseStatus\x120\n" +
	"\x14response_status_code\x18\x14 \x01(\x05R\x12responseStatusCode\x12%\n" +
	"\x0eresponse_proto\x18\x15 \x01(\tR\rresponseProto\x12)\n" +
	"\x10response_headers\x18\x16 \x01(\tR\x0fresponseHeaders\x126\n" +
	"\x17response_content_length\x18\x17 \x01(\x03R\x15responseContentLength\x12#\n" +
	"\rresponse_body\x18\x18 \x01(\fR\fresponseBody\x12\x1d\n" +
	"\n" +
	"created_at\x18\x19 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1a \x01(\x03R\tupdatedAt\x12\x1a\n" +
	"\bmetadata\x18\x1b \x01(\tR\bmetadata2n\n" +
	"\x05Burro\x12/\n" +
	"\x04Ping\x12\x12.burro.PingRequest\x1a\x13.burro.PingResponse\x124\n" +
	"\tSubscribe\x12\x17.burro.SubscribeRequest\x1a\f.burro.Event0\x01B0Z.gitlab.com/marsskom/burro/internal/proto;protob\x06proto3"

var (
	file_burro_proto_rawDescOnce sync.Once
	file_burro_proto_rawDescData []byte
)

func file_burro_proto_rawDescGZIP() []byte {
	file_burro_proto_rawDescOnce.Do(func() {
		file_burro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_burro_proto_rawDesc), len(file_burro_proto_rawDesc)))
	})
	return file_burro_proto_rawDescData
}

var file_burro_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_burro_proto_goTypes = []any{
	(*PingRequest)(nil),      // 0: burro.PingRequest
	(*PingResponse)(nil),     // 1: burro.PingResponse
	(*SubscribeRequest)(nil), // 2: burro.SubscribeRequest
	(*Event)(nil),            // 3: burro.Event
}
var file_burro_proto_depIdxs = []int32{
	0, // 0: burro.Burro.Ping:input_type -> burro.PingRequest
	2, // 1: burro.Burro.Subscribe:input_type -> burro.SubscribeRequest
	1, // 2: burro.Burro.Ping:output_type -> burro.PingResponse
	3, // 3: burro.Burro.Subscribe:output_type -> burro.Event
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_burro_proto_init() }
func file_burro_proto_init() {
	if File_burro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_burro_proto_rawDesc), len(file_burro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_burro_proto_goTypes,
		DependencyIndexes: file_burro_proto_depIdxs,
		MessageInfos:      file_burro_proto_msgTypes,
	}.Build()
	File_burro_proto = out.File
	file_burro_proto_goTypes = nil
	file_burro_proto_depIdxs = nil
}
