// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: burro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportType int32

const (
	TransportType_TRANSPORT_HTTP TransportType = 0
	TransportType_TRANSPORT_WS   TransportType = 1
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_HTTP",
		1: "TRANSPORT_WS",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_HTTP": 0,
		"TRANSPORT_WS":   1,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_burro_proto_enumTypes[0].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_burro_proto_enumTypes[0]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_CONNECT    EventType = 0
	EventType_EVENT_REQUEST    EventType = 1
	EventType_EVENT_RESPONSE   EventType = 2
	EventType_EVENT_ERROR      EventType = 3
	EventType_EVENT_CLOSE      EventType = 4
	EventType_EVENT_WS_CONNECT EventType = 10
	EventType_EVENT_WS_MESSAGE EventType = 11
	EventType_EVENT_WS_CLOSE   EventType = 12
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_CONNECT",
		1:  "EVENT_REQUEST",
		2:  "EVENT_RESPONSE",
		3:  "EVENT_ERROR",
		4:  "EVENT_CLOSE",
		10: "EVENT_WS_CONNECT",
		11: "EVENT_WS_MESSAGE",
		12: "EVENT_WS_CLOSE",
	}
	EventType_value = map[string]int32{
		"EVENT_CONNECT":    0,
		"EVENT_REQUEST":    1,
		"EVENT_RESPONSE":   2,
		"EVENT_ERROR":      3,
		"EVENT_CLOSE":      4,
		"EVENT_WS_CONNECT": 10,
		"EVENT_WS_MESSAGE": 11,
		"EVENT_WS_CLOSE":   12,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_burro_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_burro_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{1}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_burro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_burro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType []TransportType        `protobuf:"varint,1,rep,packed,name=transport_type,json=transportType,proto3,enum=burro.TransportType" json:"transport_type,omitempty"`
	EventTypes    []EventType            `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=burro.EventType" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_burro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTransportType() []TransportType {
	if x != nil {
		return x.TransportType
	}
	return nil
}

func (x *SubscribeRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type HTTPEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Proto                 string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Scheme                string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host                  string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Method                string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Url                   string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Path                  string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	ContentLength         int64                  `protobuf:"varint,7,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	RemoteAddr            string                 `protobuf:"bytes,8,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	StartTime             int64                  `protobuf:"varint,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	State                 int32                  `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`
	IsFinished            bool                   `protobuf:"varint,11,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	QueryParams           string                 `protobuf:"bytes,12,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"` // JSON
	Headers               string                 `protobuf:"bytes,13,opt,name=headers,proto3" json:"headers,omitempty"`                            // JSON
	Cookies               string                 `protobuf:"bytes,14,opt,name=cookies,proto3" json:"cookies,omitempty"`                            // JSON
	RequestBody           []byte                 `protobuf:"bytes,15,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseStatus        string                 `protobuf:"bytes,16,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseStatusCode    int32                  `protobuf:"varint,17,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	ResponseProto         string                 `protobuf:"bytes,18,opt,name=response_proto,json=responseProto,proto3" json:"response_proto,omitempty"`
	ResponseHeaders       string                 `protobuf:"bytes,19,opt,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty"` // JSON
	ResponseContentLength int64                  `protobuf:"varint,20,opt,name=response_content_length,json=responseContentLength,proto3" json:"response_content_length,omitempty"`
	ResponseBody          []byte                 `protobuf:"bytes,21,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             int64                  `protobuf:"varint,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata              string                 `protobuf:"bytes,24,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HTTPEvent) Reset() {
	*x = HTTPEvent{}
	mi := &file_burro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPEvent) ProtoMessage() {}

func (x *HTTPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPEvent.ProtoReflect.Descriptor instead.
func (*HTTPEvent) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPEvent) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *HTTPEvent) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HTTPEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HTTPEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPEvent) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *HTTPEvent) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *HTTPEvent) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *HTTPEvent) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *HTTPEvent) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *HTTPEvent) GetQueryParams() string {
	if x != nil {
		return x.QueryParams
	}
	return ""
}

func (x *HTTPEvent) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *HTTPEvent) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *HTTPEvent) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *HTTPEvent) GetResponseStatus() string {
	if x != nil {
		return x.ResponseStatus
	}
	return ""
}

func (x *HTTPEvent) GetResponseStatusCode() int32 {
	if x != nil {
		return x.ResponseStatusCode
	}
	return 0
}

func (x *HTTPEvent) GetResponseProto() string {
	if x != nil {
		return x.ResponseProto
	}
	return ""
}

func (x *HTTPEvent) GetResponseHeaders() string {
	if x != nil {
		return x.ResponseHeaders
	}
	return ""
}

func (x *HTTPEvent) GetResponseContentLength() int64 {
	if x != nil {
		return x.ResponseContentLength
	}
	return 0
}

func (x *HTTPEvent) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *HTTPEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HTTPEvent) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *HTTPEvent) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type WSEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        int32                  `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSEvent) Reset() {
	*x = WSEvent{}
	mi := &file_burro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSEvent) ProtoMessage() {}

func (x *WSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSEvent.ProtoReflect.Descriptor instead.
func (*WSEvent) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{4}
}

func (x *WSEvent) GetOpcode() int32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *WSEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *WSEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WSEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType TransportType          `protobuf:"varint,1,opt,name=transport_type,json=transportType,proto3,enum=burro.TransportType" json:"transport_type,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=burro.EventType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Http          *HTTPEvent             `protobuf:"bytes,6,opt,name=http,proto3" json:"http,omitempty"`
	Ws            *WSEvent               `protobuf:"bytes,7,opt,name=ws,proto3" json:"ws,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_burro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_burro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_burro_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetTransportType() TransportType {
	if x != nil {
		return x.TransportType
	}
	return TransportType_TRANSPORT_HTTP
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_CONNECT
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetHttp() *HTTPEvent {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Event) GetWs() *WSEvent {
	if x != nil {
		return x.Ws
	}
	return nil
}

var File_burro_proto protoreflect.FileDescriptor

const file_burro_proto_rawDesc = "" +
	"\n" +
	"\vburro.proto\x12\x05burro\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x82\x01\n" +
	"\x10SubscribeRequest\x12;\n" +
	"\x0etransport_type\x18\x01 \x03(\x0e2\x14.burro.TransportTypeR\rtransportType\x121\n" +
	"\vevent_types\x18\x02 \x03(\x0e2\x10.burro.EventTypeR\n" +
	"eventTypes\"\x87\x06\n" +
	"\tHTTPEvent\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12%\n" +
	"\x0econtent_length\x18\a \x01(\x03R\rcontentLength\x12\x1f\n" +
	"\vremote_addr\x18\b \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\x03R\tstartTime\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\x05R\x05state\x12\x1f\n" +
	"\vis_finished\x18\v \x01(\bR\n" +
	"isFinished\x12!\n" +
	"\fquery_params\x18\f \x01(\tR\vqueryParams\x12\x18\n" +
	"\aheaders\x18\r \x01(\tR\aheaders\x12\x18\n" +
	"\acookies\x18\x0e \x01(\tR\acookies\x12!\n" +
	"\frequest_body\x18\x0f \x01(\fR\vrequestBody\x12'\n" +
	"\x0fresponse_status\x18\x10 \x01(\tR\x0eresponseStatus\x120\n" +
	"\x14response_status_code\x18\x11 \x01(\x05R\x12responseStatusCode\x12%\n" +
	"\x0eresponse_proto\x18\x12 \x01(\tR\rresponseProto\x12)\n" +
	"\x10response_headers\x18\x13 \x01(\tR\x0fresponseHeaders\x126\n" +
	"\x17response_content_length\x18\x14 \x01(\x03R\x15responseContentLength\x12#\n" +
	"\rresponse_body\x18\x15 \x01(\fR\fresponseBody\x12\x1d\n" +
	"\n" +
	"created_at\x18\x16 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\x03R\tupdatedAt\x12\x1a\n" +
	"\bmetadata\x18\x18 \x01(\tR\bmetadata\"\x85\x01\n" +
	"\aWSEvent\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\x05R\x06opcode\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xfd\x01\n" +
	"\x05Event\x12;\n" +
	"\x0etransport_type\x18\x01 \x01(\x0e2\x14.burro.TransportTypeR\rtransportType\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.burro.EventTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12$\n" +
	"\x04http\x18\x06 \x01(\v2\x10.burro.HTTPEventR\x04http\x12\x1e\n" +
	"\x02ws\x18\a \x01(\v2\x0e.burro.WSEventR\x02ws*5\n" +
	"\rTransportType\x12\x12\n" +
	"\x0eTRANSPORT_HTTP\x10\x00\x12\x10\n" +
	"\fTRANSPORT_WS\x10\x01*\xa7\x01\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_CONNECT\x10\x00\x12\x11\n" +
	"\rEVENT_REQUEST\x10\x01\x12\x12\n" +
	"\x0eEVENT_RESPONSE\x10\x02\x12\x0f\n" +
	"\vEVENT_ERROR\x10\x03\x12\x0f\n" +
	"\vEVENT_CLOSE\x10\x04\x12\x14\n" +
	"\x10EVENT_WS_CONNECT\x10\n" +
	"\x12\x14\n" +
	"\x10EVENT_WS_MESSAGE\x10\v\x12\x12\n" +
	"\x0eEVENT_WS_CLOSE\x10\f2n\n" +
	"\x05Burro\x12/\n" +
	"\x04Ping\x12\x12.burro.PingRequest\x1a\x13.burro.PingResponse\x124\n" +
	"\tSubscribe\x12\x17.burro.SubscribeRequest\x1a\f.burro.Event0\x01B0Z.gitlab.com/marsskom/burro/internal/proto;protob\x06proto3"

var (
	file_burro_proto_rawDescOnce sync.Once
	file_burro_proto_rawDescData []byte
)

func file_burro_proto_rawDescGZIP() []byte {
	file_burro_proto_rawDescOnce.Do(func() {
		file_burro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_burro_proto_rawDesc), len(file_burro_proto_rawDesc)))
	})
	return file_burro_proto_rawDescData
}

var file_burro_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_burro_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_burro_proto_goTypes = []any{
	(TransportType)(0),       // 0: burro.TransportType
	(EventType)(0),           // 1: burro.EventType
	(*PingRequest)(nil),      // 2: burro.PingRequest
	(*PingResponse)(nil),     // 3: burro.PingResponse
	(*SubscribeRequest)(nil), // 4: burro.SubscribeRequest
	(*HTTPEvent)(nil),        // 5: burro.HTTPEvent
	(*WSEvent)(nil),          // 6: burro.WSEvent
	(*Event)(nil),            // 7: burro.Event
}
var file_burro_proto_depIdxs = []int32{
	0, // 0: burro.SubscribeRequest.transport_type:type_name -> burro.TransportType
	1, // 1: burro.SubscribeRequest.event_types:type_name -> burro.EventType
	0, // 2: burro.Event.transport_type:type_name -> burro.TransportType
	1, // 3: burro.Event.type:type_name -> burro.EventType
	5, // 4: burro.Event.http:type_name -> burro.HTTPEvent
	6, // 5: burro.Event.ws:type_name -> burro.WSEvent
	2, // 6: burro.Burro.Ping:input_type -> burro.PingRequest
	4, // 7: burro.Burro.Subscribe:input_type -> burro.SubscribeRequest
	3, // 8: burro.Burro.Ping:output_type -> burro.PingResponse
	7, // 9: burro.Burro.Subscribe:output_type -> burro.Event
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_burro_proto_init() }
func file_burro_proto_init() {
	if File_burro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_burro_proto_rawDesc), len(file_burro_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_burro_proto_goTypes,
		DependencyIndexes: file_burro_proto_depIdxs,
		EnumInfos:         file_burro_proto_enumTypes,
		MessageInfos:      file_burro_proto_msgTypes,
	}.Build()
	File_burro_proto = out.File
	file_burro_proto_goTypes = nil
	file_burro_proto_depIdxs = nil
}
