// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Request struct {
	ID               string
	SessionID        string
	StartTime        int64
	State            sql.NullInt64
	IsFinished       sql.NullInt64
	Metadata         sql.NullString
	CreatedAt        sql.NullInt64
	UpdatedAt        sql.NullInt64
	ReqProto         string
	ReqHost          string
	ReqMethod        string
	ReqScheme        string
	ReqUrl           string
	ReqPath          string
	ReqQueryParams   string
	ReqHeaders       string
	ReqCookies       string
	ReqContentLength int64
	ReqRemoteAddr    string
	ReqBody          []byte
	ResProto         sql.NullString
	ResStatus        sql.NullString
	ResStatusCode    sql.NullInt64
	ResHeaders       sql.NullString
	ResContentLength sql.NullInt64
	ResBody          []byte
}

type Session struct {
	ID          string
	Name        sql.NullString
	Description sql.NullString
	Metadata    sql.NullString
	CreatedAt   sql.NullInt64
	UpdatedAt   sql.NullInt64
}

type Workspace struct {
	ID        string
	Name      string
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}
