// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Request struct {
	ID           string
	SessionID    string
	Host         string
	Url          string
	Method       string
	RequestRaw   []byte
	ResponseRaw  []byte
	StartTime    int64
	State        sql.NullInt64
	IsFinished   sql.NullInt64
	Metadata     sql.NullString
	CreatedAt    sql.NullInt64
	UpdatedAt    sql.NullInt64
	ResponseBody []byte
	RequestBody  []byte
}

type Session struct {
	ID          string
	Name        sql.NullString
	Description sql.NullString
	Metadata    sql.NullString
	CreatedAt   sql.NullInt64
	UpdatedAt   sql.NullInt64
}

type Workspace struct {
	ID        string
	Name      string
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}
