// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request.sql

package database

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO request (id, session_id, host, url, method, request_raw, request_body, response_raw, response_body, start_time, state, is_finished, metadata, created_at, updated_at, scheme, path, proto, headers, cookies, query_params, content_length, remote_addr, resp_status, resp_status_code, resp_proto, resp_headers, resp_content_length)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, host, url, method, request_raw, response_raw, start_time, state, is_finished, metadata, created_at, updated_at, response_body, request_body, scheme, path, proto, headers, cookies, query_params, content_length, remote_addr, resp_status, resp_status_code, resp_proto, resp_headers, resp_content_length
`

type CreateRequestParams struct {
	ID                string
	SessionID         string
	Host              string
	Url               string
	Method            string
	RequestRaw        []byte
	RequestBody       []byte
	ResponseRaw       []byte
	ResponseBody      []byte
	StartTime         int64
	State             sql.NullInt64
	IsFinished        sql.NullInt64
	Metadata          sql.NullString
	CreatedAt         sql.NullInt64
	UpdatedAt         sql.NullInt64
	Scheme            string
	Path              string
	Proto             string
	Headers           string
	Cookies           string
	QueryParams       string
	ContentLength     int64
	RemoteAddr        string
	RespStatus        sql.NullString
	RespStatusCode    sql.NullInt64
	RespProto         sql.NullString
	RespHeaders       sql.NullString
	RespContentLength sql.NullInt64
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.ID,
		arg.SessionID,
		arg.Host,
		arg.Url,
		arg.Method,
		arg.RequestRaw,
		arg.RequestBody,
		arg.ResponseRaw,
		arg.ResponseBody,
		arg.StartTime,
		arg.State,
		arg.IsFinished,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Scheme,
		arg.Path,
		arg.Proto,
		arg.Headers,
		arg.Cookies,
		arg.QueryParams,
		arg.ContentLength,
		arg.RemoteAddr,
		arg.RespStatus,
		arg.RespStatusCode,
		arg.RespProto,
		arg.RespHeaders,
		arg.RespContentLength,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Host,
		&i.Url,
		&i.Method,
		&i.RequestRaw,
		&i.ResponseRaw,
		&i.StartTime,
		&i.State,
		&i.IsFinished,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBody,
		&i.RequestBody,
		&i.Scheme,
		&i.Path,
		&i.Proto,
		&i.Headers,
		&i.Cookies,
		&i.QueryParams,
		&i.ContentLength,
		&i.RemoteAddr,
		&i.RespStatus,
		&i.RespStatusCode,
		&i.RespProto,
		&i.RespHeaders,
		&i.RespContentLength,
	)
	return i, err
}

const getBySessionID = `-- name: GetBySessionID :many
SELECT id, session_id, host, url, method, request_raw, response_raw, start_time, state, is_finished, metadata, created_at, updated_at, response_body, request_body, scheme, path, proto, headers, cookies, query_params, content_length, remote_addr, resp_status, resp_status_code, resp_proto, resp_headers, resp_content_length FROM request WHERE session_id = ?
`

func (q *Queries) GetBySessionID(ctx context.Context, sessionID string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Host,
			&i.Url,
			&i.Method,
			&i.RequestRaw,
			&i.ResponseRaw,
			&i.StartTime,
			&i.State,
			&i.IsFinished,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponseBody,
			&i.RequestBody,
			&i.Scheme,
			&i.Path,
			&i.Proto,
			&i.Headers,
			&i.Cookies,
			&i.QueryParams,
			&i.ContentLength,
			&i.RemoteAddr,
			&i.RespStatus,
			&i.RespStatusCode,
			&i.RespProto,
			&i.RespHeaders,
			&i.RespContentLength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequest = `-- name: GetRequest :one
SELECT id, session_id, host, url, method, request_raw, response_raw, start_time, state, is_finished, metadata, created_at, updated_at, response_body, request_body, scheme, path, proto, headers, cookies, query_params, content_length, remote_addr, resp_status, resp_status_code, resp_proto, resp_headers, resp_content_length FROM request WHERE id = ?
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Host,
		&i.Url,
		&i.Method,
		&i.RequestRaw,
		&i.ResponseRaw,
		&i.StartTime,
		&i.State,
		&i.IsFinished,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBody,
		&i.RequestBody,
		&i.Scheme,
		&i.Path,
		&i.Proto,
		&i.Headers,
		&i.Cookies,
		&i.QueryParams,
		&i.ContentLength,
		&i.RemoteAddr,
		&i.RespStatus,
		&i.RespStatusCode,
		&i.RespProto,
		&i.RespHeaders,
		&i.RespContentLength,
	)
	return i, err
}

const updateRequest = `-- name: UpdateRequest :exec
UPDATE request
SET state = ?, is_finished = ?, metadata = ?, updated_at = ?, response_raw = ?, response_body = ?, resp_status = ?, resp_status_code = ?, resp_proto = ?, resp_headers = ?, resp_content_length = ?
WHERE id = ?
`

type UpdateRequestParams struct {
	State             sql.NullInt64
	IsFinished        sql.NullInt64
	Metadata          sql.NullString
	UpdatedAt         sql.NullInt64
	ResponseRaw       []byte
	ResponseBody      []byte
	RespStatus        sql.NullString
	RespStatusCode    sql.NullInt64
	RespProto         sql.NullString
	RespHeaders       sql.NullString
	RespContentLength sql.NullInt64
	ID                string
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateRequest,
		arg.State,
		arg.IsFinished,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ResponseRaw,
		arg.ResponseBody,
		arg.RespStatus,
		arg.RespStatusCode,
		arg.RespProto,
		arg.RespHeaders,
		arg.RespContentLength,
		arg.ID,
	)
	return err
}

const upsertRequest = `-- name: UpsertRequest :exec
INSERT INTO request (id, session_id, host, url, method, request_raw, request_body, response_raw, response_body, start_time, state, is_finished, metadata, created_at, updated_at, scheme, path, proto, headers, cookies, query_params, content_length, remote_addr, resp_status, resp_status_code, resp_proto, resp_headers, resp_content_length)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
state = excluded.state,
is_finished = excluded.is_finished,
metadata = excluded.metadata,
updated_at = excluded.updated_at,
response_raw = excluded.response_raw,
response_body = excluded.response_body,
resp_status = excluded.resp_status,
resp_status_code = excluded.resp_status_code,
resp_proto = excluded.resp_proto,
resp_headers = excluded.resp_headers,
resp_content_length = excluded.resp_content_length
`

type UpsertRequestParams struct {
	ID                string
	SessionID         string
	Host              string
	Url               string
	Method            string
	RequestRaw        []byte
	RequestBody       []byte
	ResponseRaw       []byte
	ResponseBody      []byte
	StartTime         int64
	State             sql.NullInt64
	IsFinished        sql.NullInt64
	Metadata          sql.NullString
	CreatedAt         sql.NullInt64
	UpdatedAt         sql.NullInt64
	Scheme            string
	Path              string
	Proto             string
	Headers           string
	Cookies           string
	QueryParams       string
	ContentLength     int64
	RemoteAddr        string
	RespStatus        sql.NullString
	RespStatusCode    sql.NullInt64
	RespProto         sql.NullString
	RespHeaders       sql.NullString
	RespContentLength sql.NullInt64
}

func (q *Queries) UpsertRequest(ctx context.Context, arg UpsertRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertRequest,
		arg.ID,
		arg.SessionID,
		arg.Host,
		arg.Url,
		arg.Method,
		arg.RequestRaw,
		arg.RequestBody,
		arg.ResponseRaw,
		arg.ResponseBody,
		arg.StartTime,
		arg.State,
		arg.IsFinished,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Scheme,
		arg.Path,
		arg.Proto,
		arg.Headers,
		arg.Cookies,
		arg.QueryParams,
		arg.ContentLength,
		arg.RemoteAddr,
		arg.RespStatus,
		arg.RespStatusCode,
		arg.RespProto,
		arg.RespHeaders,
		arg.RespContentLength,
	)
	return err
}
