// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request.sql

package database

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO request (id, session_id, host, url, method, request_raw, request_body, response_raw, response_body, start_time, state, is_finished, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, host, url, method, request_raw, response_raw, start_time, state, is_finished, metadata, created_at, updated_at, response_body, request_body
`

type CreateRequestParams struct {
	ID           string
	SessionID    string
	Host         string
	Url          string
	Method       string
	RequestRaw   []byte
	RequestBody  []byte
	ResponseRaw  []byte
	ResponseBody []byte
	StartTime    int64
	State        sql.NullInt64
	IsFinished   sql.NullInt64
	Metadata     sql.NullString
	CreatedAt    sql.NullInt64
	UpdatedAt    sql.NullInt64
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.ID,
		arg.SessionID,
		arg.Host,
		arg.Url,
		arg.Method,
		arg.RequestRaw,
		arg.RequestBody,
		arg.ResponseRaw,
		arg.ResponseBody,
		arg.StartTime,
		arg.State,
		arg.IsFinished,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Host,
		&i.Url,
		&i.Method,
		&i.RequestRaw,
		&i.ResponseRaw,
		&i.StartTime,
		&i.State,
		&i.IsFinished,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBody,
		&i.RequestBody,
	)
	return i, err
}

const getBySessionID = `-- name: GetBySessionID :many
SELECT id, session_id, host, url, method, request_raw, response_raw, start_time, state, is_finished, metadata, created_at, updated_at, response_body, request_body FROM request WHERE session_id = ?
`

func (q *Queries) GetBySessionID(ctx context.Context, sessionID string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Host,
			&i.Url,
			&i.Method,
			&i.RequestRaw,
			&i.ResponseRaw,
			&i.StartTime,
			&i.State,
			&i.IsFinished,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponseBody,
			&i.RequestBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequest = `-- name: GetRequest :one
SELECT id, session_id, host, url, method, request_raw, response_raw, start_time, state, is_finished, metadata, created_at, updated_at, response_body, request_body FROM request WHERE id = ?
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Host,
		&i.Url,
		&i.Method,
		&i.RequestRaw,
		&i.ResponseRaw,
		&i.StartTime,
		&i.State,
		&i.IsFinished,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBody,
		&i.RequestBody,
	)
	return i, err
}

const updateRequest = `-- name: UpdateRequest :exec
UPDATE request
SET request_raw = ?, request_body = ?, response_raw = ?, response_body = ?, state = ?, is_finished = ?, metadata = ?, updated_at = ?
WHERE id = ?
`

type UpdateRequestParams struct {
	RequestRaw   []byte
	RequestBody  []byte
	ResponseRaw  []byte
	ResponseBody []byte
	State        sql.NullInt64
	IsFinished   sql.NullInt64
	Metadata     sql.NullString
	UpdatedAt    sql.NullInt64
	ID           string
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateRequest,
		arg.RequestRaw,
		arg.RequestBody,
		arg.ResponseRaw,
		arg.ResponseBody,
		arg.State,
		arg.IsFinished,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertRequest = `-- name: UpsertRequest :exec
INSERT INTO request (id, session_id, host, url, method, request_raw, request_body, response_raw, response_body, start_time, state, is_finished, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
request_raw = excluded.request_raw,
request_body = excluded.request_body,
response_raw = excluded.response_raw,
response_body = excluded.response_body,
state = excluded.state,
is_finished = excluded.is_finished,
metadata = excluded.metadata,
updated_at = excluded.updated_at
`

type UpsertRequestParams struct {
	ID           string
	SessionID    string
	Host         string
	Url          string
	Method       string
	RequestRaw   []byte
	RequestBody  []byte
	ResponseRaw  []byte
	ResponseBody []byte
	StartTime    int64
	State        sql.NullInt64
	IsFinished   sql.NullInt64
	Metadata     sql.NullString
	CreatedAt    sql.NullInt64
	UpdatedAt    sql.NullInt64
}

func (q *Queries) UpsertRequest(ctx context.Context, arg UpsertRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertRequest,
		arg.ID,
		arg.SessionID,
		arg.Host,
		arg.Url,
		arg.Method,
		arg.RequestRaw,
		arg.RequestBody,
		arg.ResponseRaw,
		arg.ResponseBody,
		arg.StartTime,
		arg.State,
		arg.IsFinished,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
