// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package database

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (id, name, description, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, description, metadata, created_at, updated_at
`

type CreateSessionParams struct {
	ID          string
	Name        sql.NullString
	Description sql.NullString
	Metadata    sql.NullString
	CreatedAt   sql.NullInt64
	UpdatedAt   sql.NullInt64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT id, name, description, metadata, created_at, updated_at FROM session
`

func (q *Queries) GetAll(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, name, description, metadata, created_at, updated_at FROM session WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE session
SET name = ?, description = ?, metadata = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	Name        sql.NullString
	Description sql.NullString
	Metadata    sql.NullString
	UpdatedAt   sql.NullInt64
	ID          string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.Name,
		arg.Description,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO session (id, name, description, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
name = excluded.name,
description = excluded.description,
metadata = excluded.metadata,
updated_at = excluded.updated_at
`

type UpsertSessionParams struct {
	ID          string
	Name        sql.NullString
	Description sql.NullString
	Metadata    sql.NullString
	CreatedAt   sql.NullInt64
	UpdatedAt   sql.NullInt64
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
