// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package database

import (
	"context"
	"database/sql"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace (id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, updated_at FROM workspace WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, created_at, updated_at FROM workspace WHERE name = ?
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspace SET updated_at = ? WHERE id = ?
`

type UpdateWorkspaceParams struct {
	UpdatedAt sql.NullInt64
	ID        string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace, arg.UpdatedAt, arg.ID)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspace (id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
updated_at = excluded.updated_at
`

type UpsertWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
