core:
  log_level: debug
  plugins:
    dir: "plugins"
    config: "config.yml"

proxy:
  port: 8080
  host: 0.0.0.0

plugins:
  logger:

  policy: # separate config

  harexport:
    file: "%session%-%datetime%.har"
    override: true
