core:
  log_level: error
  plugins:
    dir: "plugins"
    config: "config.yml"

proxy:
  listen: localhost:8080

grpc:
  enabled: true
  listen: localhost:7777

tls:
  enabled: false
  cert:
  key:

plugins:
  logger:

  policy: # separate config

  harexport:
    file: "%session%-%datetime%.har"
    override: true
