core:
  log_level: info
  plugins:
    dir: plugins
    config: config.yml

proxy:
  listen: localhost:8080

grpc:
  enabled: true
  debug: false
  listen: localhost:7777

tls:
  enabled: false
  insecure: false
  cert:
  key:

plugins:
  logger:

  policy: # separate config

  harexport:
    enabled: false
    file: "%session%-%datetime%.har"
    override: true
